name: kidney-exchange
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.3
  - pip=20.1.1
  - graph-tool=2.33
  - pandas=1.0.5
  - scipy=1.5.0
  - numpy=1.18.5
  - xlrd=1.2.0
  - flask=1.1.2
  - gunicorn=20.0.4
  - flask-sqlalchemy=2.4.1
  - pip:
      - psycopg2-binary==2.8.5
