version: '3.7'
services:
  backend:
    image: mildblue/kidney-exchange
    deploy:
      restart_policy:
        condition: always
    env_file:
      - .env.prod
    ports:
      - 9090:8080
    depends_on:
      - db

  db:
    image: postgres:12.2
    deploy:
      restart_policy:
        condition: always
    env_file:
      - .env.prod
    ports:
      - 9092:5432
    volumes:
      - kidney-exchange-postgres-prod:/var/lib/postgresql/data/

volumes:
  kidney-exchange-postgres-prod: