version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: txmatching
    env_file:
      - .env.pub
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - /var/log/txmatching:/logs

  db:
    image: postgres:12.2
    env_file:
      - .env.pub
    ports:
      - 5432:5432
    volumes:
      - txmatching-postgres:/var/lib/postgresql/data/

volumes:
  txmatching-postgres:
