version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: datavid19/kidney-exchange
    env_file:
      - .env.pub
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:12.2
    env_file:
      - .env.pub
    ports:
      - 5432:5432
    volumes:
      - kidney-exchange-postgres:/var/lib/postgresql/data/

volumes:
  kidney-exchange-postgres:
