# Do not forgot to update other docker-compose files, especially in project-configuration repository.
version: '3.8'
services:
  proxy:
    image: traefik:v2.4
    container_name: proxy
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.resolver.acme.email=services@mild.blue"
      - "--certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - 443:443
      - 80:80
    volumes:
      - /srv/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  backend:
    image: 913797522953.dkr.ecr.eu-west-1.amazonaws.com/stg-txm
    container_name: txm
    env_file:
      - .env
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - /var/log/mildblue/txmatching:/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.txm.loadbalancer.server.port=8080"
      - "traefik.http.routers.txm.rule=Host(`txm.stg.mild.blue`)"
      - "traefik.http.routers.txm.entrypoints=websecure"
      - "traefik.http.routers.txm.tls.certresolver=resolver"

  db:
    image: postgres:13.1
    container_name: db
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always
    volumes:
      - txmatching-postgres:/var/lib/postgresql/data/

volumes:
  txmatching-postgres: