#services:
#  traefik:
#    image: "traefik:v2.4"
#    container_name: "traefik"
#    command:
#      - "--log.level=DEBUG"
#      - "--api.insecure=true"
#      - "--providers.docker=true"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.http.address=:80"
#      - "--entrypoints.https.address=:443"
#      - "--certificatesresolvers.mb_resolver.acme.tlschallenge=true"
#      - "--certificatesresolvers.mb_resolver.acme.email=services@mild.blue"
#      - "--certificatesresolvers.mb_resolver.acme.storage=/letsencrypt/acme.json"
#
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - "/srv/letsencrypt:/letsencrypt"
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#
#  whoami:
#    image: "traefik/whoami"
#    container_name: "simple-service"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.whoami.rule=Host(`txm.stg.mild.blue`)"
#      - "traefik.http.routers.whoami.tls.certresolver=mb_resolver"
#      - "traefik.http.routers.whoami.entrypoints=https"


version: "3.8"
services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.resolver.acme.tlschallenge=true"
      - "--certificatesresolvers.resolver.acme.email=lukas@mild.blue"
      - "--certificatesresolvers.resolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/srv/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  default:
    external:
      name: mildblue
