version: '3.7'
services:
  backend:
    image: mildblue/txmatching:TAG
    env_file:
      - .env
    ports:
      - 31944:8080
    restart: always
    depends_on:
      - db

  db:
    image: postgres:12.2
    env_file:
      - .env
    ports:
      - 35432:5432
    restart: always
    volumes:
      - txmatching-postgres:/var/lib/postgresql/data/

volumes:
  txmatching-postgres: