# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mildblue/txmatching:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_URL
            - name: SMS_SERVICE_URL
                valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: SMS_SERVICE_URL
            - name: SMS_SERVICE_SENDER
                valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: SMS_SERVICE_SENDER
            - name: SMS_SERVICE_LOGIN
                valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: SMS_SERVICE_LOGIN
            - name: SMS_SERVICE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: secrets
                    key: SMS_SERVICE_PASSWORD
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31944
      protocol: TCP
      name: http
  selector:
    app: backend
