apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  POSTGRES_DB: {{POSTGRES_DB}}
  POSTGRES_USER: {{POSTGRES_USER}}
  POSTGRES_PASSWORD: {{POSTGRES_PASSWORD}}
  POSTGRES_URL: {{POSTGRES_URL}}
  JWT_SECRET: {{JWT_SECRET}}
  JWT_EXPIRATION_DAYS: 30
