name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_server:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Set envs
        # set release version to the latest commit
        run: echo "RELEASE_VERSION=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build docker image, push if the branch is master
        uses: docker/build-push-action@v1
        with:
          # login to repo
          repository: mildblue/txmatching
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # pass release_version
          build_args: release_version=${{ env.RELEASE_VERSION }}
          # tag the image with latest git tag
          tag_with_ref: true
          # add labels from the git
          add_git_labels: true
          # push only if this is build in the master branch
          push: ${{ startsWith(github.ref, 'refs/heads/master') }}

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build_server
    steps:
      - name: Redeploy application
        if: ${{ startsWith(github.ref, 'refs/heads/master') }}
        env:
          AUTH: ${{ secrets.DEPLOYMENT_TOKEN }}
        run: |
          curl 188.166.192.68:9091/redeploy --header "auth: $AUTH"
